# Site Settings
name: LonTon
title: LonTon | Ký ức tuổi thơ
description: LonTon luôn cập nhật, chia sẻ những thông điệp vui vẻ mang đến cho bạn tinh thần thoải mái trong cuộc sống, khi gợi nhớ lại những kí ức, cảm xúc về tuổi thơ trong mỗi chúng ta.
tags:
  - chia sẻ
  - thông điệp
  - ký ức
show_hero: true
menu:
  - title: Bài viết
    url: /
  # - title: About
  #   url: /about
  # - title: Contact
  #   url: /contact
  # - title: Feed
  #   url: /feed.xml
email: vanha.ptit@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id


# Social Media Settings
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "vi"
categories_folder: c
sent_message_url: "/contact/message-sent/"


translations:
  text:
    new_post: Bài viết mới
    see_also: Xem thêm
    search: Tìm kiếm
    author: Tác giả
    share: Chia sẻ
    comments: Bình luận
  button:
    read_now: Đọc luôn
    share_on_twitter: Chia sẻ bài lên Twitter
    share_on_facebook: Chia sẻ bài lên Facebook
  pagination:
    page: Trang
    of: đến
    next_page: Đi tiếp
    next_post: Lùi lại
  recommendation:
    text: Bạn muốn đọc tiếp chứ?
    back_btn: Trở lên đầu trang
  error_404:
    title: Oh không thấy bài đâu rồi :(
    message: Xin lỗi nhé!. Bạn vui lòng đọc tạm bài khác nhé.
    image_alt: 404 - Oh không thấy bài đâu rồi
  contact:
    title: Nói chuyện với tôi
    subject: Liên lạc mới!
    submit_btn: Gửi
    placeholders:
      name: Tên của bạn là gì
      email: Nhập vào hòm thư của bạn
      message: Nội dung nhắn gửi
    errors:
      locale: vi
      empty_name: Vui lòng nhập tên
      empty_email: Vui lòng nhập email
      invalid_email: Email không đúng định dạng
      empty_message: Hãy nhập nội dung
    after_send:
      title: Đã gửi đi!
      message: Cảm ơn bạn đã gửi thông tin. Chúng tôi sẽ phản hồi lại sớm nhất có thể.
button:
  read_now: Đọc luôn
pagination:
  next_post: Bài viết tiếp theo
  next_page: Trang sau
  page: Trang
  of: đến
recommendation:
  back_btn: Lên đầu trang
contact:
  errors:
    locale: vi


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title.html
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.1

